// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WH.Api.Data;

#nullable disable

namespace WH.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240322110054_Add_ИсточникЗаявки_Должность")]
    partial class Add_ИсточникЗаявки_Должность
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WH.Api.Jobs.JobResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Begin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("LoadingJobResults", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.AccumulationRegister.AccumulationRegisterВыручкаИСебестоимостьПродажRecordType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date")
                        .HasAnnotation("Relational:JsonPropertyName", "Period");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("Recorder")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Recorder_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ВидДеятельностиНДС")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ВидЗапасов_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ДокументДвижения")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ДокументДвижения_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("ДопРасходы")
                        .HasColumnType("float");

                    b.Property<double>("ДопРасходыБезНДС")
                        .HasColumnType("float");

                    b.Property<string>("ЗаказКлиента")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ЗаказКлиента_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Количество")
                        .HasColumnType("float");

                    b.Property<string>("Менеджер_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("НалогообложениеНДС")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Номенклатура_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Партия")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Партия_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Партнер_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Подразделение_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("РазделУчета")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("РасчетНеЗавершен")
                        .HasColumnType("bit");

                    b.Property<bool>("РасчетПартий")
                        .HasColumnType("bit");

                    b.Property<bool>("РасчетСебестоимости")
                        .HasColumnType("bit");

                    b.Property<string>("Склад")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Склад_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Соглашение_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("Стоимость")
                        .HasColumnType("float");

                    b.Property<double>("СтоимостьБезНДС")
                        .HasColumnType("float");

                    b.Property<double>("СуммаАвтоматическойСкидки")
                        .HasColumnType("float");

                    b.Property<double>("СуммаВыручки")
                        .HasColumnType("float");

                    b.Property<double>("СуммаВыручкиБезНДС")
                        .HasColumnType("float");

                    b.Property<double>("СуммаРучнойСкидки")
                        .HasColumnType("float");

                    b.Property<string>("ТипЗапасов")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ХозяйственнаяОперация")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AccumulationRegister_ВыручкаИСебестоимостьПродаж_RecordType", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.AccumulationRegister.AccumulationRegisterВыручкаИСебестоимостьПродажTurnovers", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<string>("ВидДеятельностиНДС")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ВидЗапасов_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("ДопРасходы")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "ДопРасходыTurnover");

                    b.Property<double>("ДопРасходыБезНДС")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "ДопРасходыБезНДСTurnover");

                    b.Property<string>("ЗаказКлиента")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ЗаказКлиента_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Количество")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "КоличествоTurnover");

                    b.Property<string>("Менеджер_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Номенклатура_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Партнер_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Подразделение_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("РазделУчета")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Склад")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Склад_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Соглашение_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("Стоимость")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "СтоимостьTurnover");

                    b.Property<double>("СтоимостьБезНДС")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "СтоимостьБезНДСTurnover");

                    b.Property<double>("СуммаАвтоматическойСкидки")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "СуммаАвтоматическойСкидкиTurnover");

                    b.Property<double>("СуммаВыручки")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "СуммаВыручкиTurnover");

                    b.Property<double>("СуммаВыручкиБезНДС")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "СуммаВыручкиБезНДСTurnover");

                    b.Property<double>("СуммаРучнойСкидки")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "СуммаРучнойСкидкиTurnover");

                    b.Property<string>("ТипЗапасов")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Трудозатраты")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "ТрудозатратыTurnover");

                    b.Property<string>("ХозяйственнаяОперация")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AccumulationRegister_ВыручкаИСебестоимостьПродаж_Turnovers", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.AccumulationRegister.AccumulationRegisterЗакупкиRecordType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date")
                        .HasAnnotation("Relational:JsonPropertyName", "Period");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("Recorder")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Recorder_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ВидЗапасов_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("Количество")
                        .HasColumnType("float");

                    b.Property<string>("Менеджер_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Номенклатура_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Организация_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Партнер_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Подразделение_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("РасчетСебестоимости")
                        .HasColumnType("bit");

                    b.Property<string>("Склад")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Склад_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Стоимость")
                        .HasColumnType("float");

                    b.Property<double>("СтоимостьБезНДС")
                        .HasColumnType("float");

                    b.Property<double>("Сумма")
                        .HasColumnType("float");

                    b.Property<double>("СуммаБезНДС")
                        .HasColumnType("float");

                    b.Property<double>("СуммаДопРасходов")
                        .HasColumnType("float");

                    b.Property<double>("СуммаДопРасходовБезНДС")
                        .HasColumnType("float");

                    b.Property<double>("СуммаСкидки")
                        .HasColumnType("float");

                    b.Property<string>("ТипЗапасов")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ХозяйственнаяОперация")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AccumulationRegister_Закупки_RecordType", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.AccumulationRegister.AccumulationRegisterТоварыНаСкладахBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<double>("ВНаличииBalance")
                        .HasColumnType("float");

                    b.Property<string>("Номенклатура_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Склад_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.ToTable("AccumulationRegister_ТоварыНаСкладах_Balance", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.AccumulationRegister.AccumulationRegisterТоварыНаСкладахBalanceAndTurnovers", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<double>("ВНаличииClosingBalance")
                        .HasColumnType("float");

                    b.Property<double>("ВНаличииExpense")
                        .HasColumnType("float");

                    b.Property<double>("ВНаличииOpeningBalance")
                        .HasColumnType("float");

                    b.Property<double>("ВНаличииReceipt")
                        .HasColumnType("float");

                    b.Property<double>("ВНаличииTurnover")
                        .HasColumnType("float");

                    b.Property<string>("Номенклатура_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Склад_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.ToTable("AccumulationRegister_ТоварыНаСкладах_BalanceAndTurnovers", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Catalog.CatalogБизнесРегионы", b =>
                {
                    b.Property<string>("Ref_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Parent_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Ref_Key");

                    b.ToTable("Catalog_БизнесРегионы", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Catalog.CatalogВидыДеятельности", b =>
                {
                    b.Property<string>("Ref_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("bit");

                    b.Property<string>("Parent_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Ref_Key");

                    b.ToTable("Catalog_ВидыДеятельности", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Catalog.CatalogВидыНоменклатуры", b =>
                {
                    b.Property<string>("Ref_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("bit");

                    b.Property<string>("Parent_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Ref_Key");

                    b.ToTable("Catalog_ВидыНоменклатуры", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Catalog.CatalogВидыЦен", b =>
                {
                    b.Property<string>("Ref_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("bit");

                    b.Property<string>("Parent_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("БазовыйВидЦены_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ВариантОкругления")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Идентификатор")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ИспользоватьПриВыпускеПродукции")
                        .HasColumnType("bit");

                    b.Property<bool>("ИспользоватьПриПередачеМеждуОрганизациями")
                        .HasColumnType("bit");

                    b.Property<bool>("ИспользоватьПриПередачеПродукцииДавальцу")
                        .HasColumnType("bit");

                    b.Property<bool>("ИспользоватьПриПродаже")
                        .HasColumnType("bit");

                    b.Property<double>("Наценка")
                        .HasColumnType("float");

                    b.Property<bool>("Округлять")
                        .HasColumnType("bit");

                    b.Property<bool>("ОкруглятьВБольшуюСторону")
                        .HasColumnType("bit");

                    b.Property<double>("ПорогСрабатывания")
                        .HasColumnType("float");

                    b.Property<int>("РеквизитДопУпорядочивания")
                        .HasColumnType("int");

                    b.Property<string>("СпособЗаданияЦены")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Статус")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("ТочностьОкругления")
                        .HasColumnType("float");

                    b.Property<bool>("УстанавливатьЦенуПриВводеНаОсновании")
                        .HasColumnType("bit");

                    b.Property<string>("Формула")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ЦенаВключаетНДС")
                        .HasColumnType("bit");

                    b.HasKey("Ref_Key");

                    b.ToTable("Catalog_ВидыЦен", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Catalog.CatalogЗначенияСвойствОбъектов", b =>
                {
                    b.Property<string>("Ref_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("bit");

                    b.Property<string>("Owner_Key")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Parent_Key")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Ref_Key");

                    b.ToTable("Catalog_ЗначенияСвойствОбъектов", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Catalog.CatalogНоменклатура", b =>
                {
                    b.Property<string>("Ref_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("bit");

                    b.Property<string>("Parent_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Артикул")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("БазоваяНоменклатура_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<double?>("ВесЗнаменатель")
                        .HasColumnType("float");

                    b.Property<double?>("ВесЧислитель")
                        .HasColumnType("float");

                    b.Property<string>("ВидНоменклатуры_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ПодвидНоменклатуры_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ТипНоменклатуры")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ТипУпаковки_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Ref_Key");

                    b.ToTable("Catalog_Номенклатура", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Catalog.CatalogПартнеры", b =>
                {
                    b.Property<string>("Ref_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Parent_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("БизнесРегион_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("ДатаРегистрации")
                        .HasColumnType("Date");

                    b.Property<string>("Доброга_ЕмкостьПотенциальная")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Клиент")
                        .HasColumnType("bit");

                    b.Property<bool>("Конкурент")
                        .HasColumnType("bit");

                    b.Property<string>("ОсновнойМенеджер_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("Перевозчик")
                        .HasColumnType("bit");

                    b.Property<bool>("Поставщик")
                        .HasColumnType("bit");

                    b.Property<bool>("ПрочиеОтношения")
                        .HasColumnType("bit");

                    b.Property<string>("ЮрФизЛицо")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Ref_Key");

                    b.ToTable("Catalog_Партнеры", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Catalog.CatalogПартнерыVip", b =>
                {
                    b.Property<string>("Партнер_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Партнер_Key");

                    b.ToTable("Catalog_Партнеры_Vip", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Catalog.CatalogПартнерыВидыДеятельности", b =>
                {
                    b.Property<string>("Ref_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("ВидДеятельности_Key")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Ref_Key", "LineNumber");

                    b.ToTable("Catalog_Партнеры_ВидыДеятельности", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Catalog.CatalogПодвидыНоменклатуры", b =>
                {
                    b.Property<string>("Ref_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("bit");

                    b.Property<string>("Parent_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Ref_Key");

                    b.ToTable("Catalog_ПодвидыНоменклатуры", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Catalog.CatalogПользователи", b =>
                {
                    b.Property<string>("Ref_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Доброга_СхемаПредприятия_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Должность")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "Доброга_Должность");

                    b.Property<string>("Подразделение_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Ref_Key");

                    b.ToTable("Catalog_Пользователи", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Catalog.CatalogПричиныОтменыЗаказовКлиентов", b =>
                {
                    b.Property<string>("Ref_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Ref_Key");

                    b.ToTable("Catalog_ПричиныОтменыЗаказовКлиентов", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Catalog.CatalogСклады", b =>
                {
                    b.Property<string>("Ref_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("bit");

                    b.Property<string>("Parent_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("БизнесРегион_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Подразделение_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ТипСклада")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Ref_Key");

                    b.ToTable("Catalog_Склады", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Catalog.CatalogСоглашенияСКлиентами", b =>
                {
                    b.Property<string>("Ref_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Номер")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Партнер_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Соглашение_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Статус")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Ref_Key");

                    b.ToTable("Catalog_СоглашенияСКлиентами", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Catalog.CatalogСхемаПредприятия", b =>
                {
                    b.Property<string>("Ref_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Parent_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Ref_Key");

                    b.ToTable("Catalog_СхемаПредприятия", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Catalog.CatalogУпаковкиЕдиницыИзмерения", b =>
                {
                    b.Property<string>("Ref_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Owner")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Owner_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Parent_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("Безразмерная")
                        .HasColumnType("bit");

                    b.Property<double>("Вес")
                        .HasColumnType("float");

                    b.Property<string>("ВесЕдиницаИзмерения_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ЕдиницаИзмерения_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("Знаменатель")
                        .HasColumnType("float");

                    b.Property<int>("КоличествоУпаковок")
                        .HasColumnType("int");

                    b.Property<string>("ТипУпаковки")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Числитель")
                        .HasColumnType("float");

                    b.HasKey("Ref_Key");

                    b.ToTable("Catalog_УпаковкиЕдиницыИзмерения", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Document.DocumentЗаказКлиента", b =>
                {
                    b.Property<string>("Ref_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<string>("Number")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ИсточникЗаявки_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasAnnotation("Relational:JsonPropertyName", "Доброга_ИсточникЗаявки_Key");

                    b.Property<string>("Менеджер_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("НалогообложениеНДС")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Партнер_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Подразделение_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("СкидкиРассчитаны")
                        .HasColumnType("bit");

                    b.Property<string>("Склад_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("Согласован")
                        .HasColumnType("bit");

                    b.Property<string>("Статус")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("СуммаДокумента")
                        .HasColumnType("float");

                    b.Property<string>("ХозяйственнаяОперация")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ЦенаВключаетНДС")
                        .HasColumnType("bit");

                    b.HasKey("Ref_Key");

                    b.ToTable("Document_ЗаказКлиента", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Document.DocumentЗаказКлиентаТовары", b =>
                {
                    b.Property<string>("Ref_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("ВидЦены_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("ДатаОтгрузки")
                        .HasColumnType("datetime2");

                    b.Property<int>("КодСтроки")
                        .HasColumnType("int");

                    b.Property<double>("Количество")
                        .HasColumnType("float");

                    b.Property<double>("КоличествоУпаковок")
                        .HasColumnType("float");

                    b.Property<string>("Номенклатура_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("Отменено")
                        .HasColumnType("bit");

                    b.Property<string>("ПричинаОтмены_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("ПроцентАвтоматическойСкидки")
                        .HasColumnType("float");

                    b.Property<double>("ПроцентРучнойСкидки")
                        .HasColumnType("float");

                    b.Property<string>("Склад_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("СтавкаНДС")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Сумма")
                        .HasColumnType("float");

                    b.Property<double>("СуммаАвтоматическойСкидки")
                        .HasColumnType("float");

                    b.Property<double>("СуммаНДС")
                        .HasColumnType("float");

                    b.Property<double>("СуммаРучнойСкидки")
                        .HasColumnType("float");

                    b.Property<double>("СуммаСНДС")
                        .HasColumnType("float");

                    b.Property<string>("Упаковка_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("Цена")
                        .HasColumnType("float");

                    b.HasKey("Ref_Key", "LineNumber");

                    b.ToTable("Document_ЗаказКлиента_Товары", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Document.DocumentОтчетОРозничныхПродажах", b =>
                {
                    b.Property<string>("Ref_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<string>("Number")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ВидЦены_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("НалогообложениеНДС")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ответственный_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Подразделение_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Склад_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("СуммаДокумента")
                        .HasColumnType("float");

                    b.Property<bool>("ЦенаВключаетНДС")
                        .HasColumnType("bit");

                    b.HasKey("Ref_Key");

                    b.ToTable("Document_ОтчетОРозничныхПродажах", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Document.DocumentОтчетОРозничныхПродажахТовары", b =>
                {
                    b.Property<string>("ИдентификаторСтроки")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("Ref_Key")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("Количество")
                        .HasColumnType("float");

                    b.Property<double>("КоличествоУпаковок")
                        .HasColumnType("float");

                    b.Property<string>("Номенклатура_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Партнер_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("ПроцентРучнойСкидки")
                        .HasColumnType("float");

                    b.Property<string>("СтавкаНДС")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Сумма")
                        .HasColumnType("float");

                    b.Property<double>("СуммаНДС")
                        .HasColumnType("float");

                    b.Property<double>("СуммаРучнойСкидки")
                        .HasColumnType("float");

                    b.Property<string>("Упаковка_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("Цена")
                        .HasColumnType("float");

                    b.HasKey("ИдентификаторСтроки");

                    b.HasIndex("Ref_Key");

                    b.ToTable("Document_ОтчетОРозничныхПродажах_Товары", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Document.DocumentРеализацияТоваровУслуг", b =>
                {
                    b.Property<string>("Ref_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<string>("Number")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ЗаказКлиента")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ЗаказКлиента_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ИсточникЗаявки_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasAnnotation("Relational:JsonPropertyName", "Доброга_ИсточникЗаявки_Key");

                    b.Property<string>("Менеджер_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("НалогообложениеНДС")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Партнер_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Подразделение_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("РеализацияПоЗаказам")
                        .HasColumnType("bit");

                    b.Property<bool>("СкидкиРассчитаны")
                        .HasColumnType("bit");

                    b.Property<string>("Склад_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("Согласован")
                        .HasColumnType("bit");

                    b.Property<string>("Статус")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("СуммаДокумента")
                        .HasColumnType("float");

                    b.Property<string>("ХозяйственнаяОперация")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ЦенаВключаетНДС")
                        .HasColumnType("bit");

                    b.HasKey("Ref_Key");

                    b.ToTable("Document_РеализацияТоваровУслуг", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Document.DocumentРеализацияТоваровУслугТовары", b =>
                {
                    b.Property<string>("ИдентификаторСтроки")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("Ref_Key")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ВидЦены_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ЗаказКлиента")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ЗаказКлиента_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("КодСтроки")
                        .HasColumnType("int");

                    b.Property<double>("Количество")
                        .HasColumnType("float");

                    b.Property<double>("КоличествоУпаковок")
                        .HasColumnType("float");

                    b.Property<string>("Номенклатура_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("ПроцентАвтоматическойСкидки")
                        .HasColumnType("float");

                    b.Property<double>("ПроцентРучнойСкидки")
                        .HasColumnType("float");

                    b.Property<string>("Склад_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("СтавкаНДС")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Сумма")
                        .HasColumnType("float");

                    b.Property<double>("СуммаАвтоматическойСкидки")
                        .HasColumnType("float");

                    b.Property<double>("СуммаНДС")
                        .HasColumnType("float");

                    b.Property<double>("СуммаРучнойСкидки")
                        .HasColumnType("float");

                    b.Property<double>("СуммаСНДС")
                        .HasColumnType("float");

                    b.Property<string>("Упаковка_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("Цена")
                        .HasColumnType("float");

                    b.HasKey("ИдентификаторСтроки");

                    b.HasIndex("Ref_Key");

                    b.ToTable("Document_РеализацияТоваровУслуг_Товары", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.InformationRegister.InformationRegisterЦеныНоменклатурыRecordType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date")
                        .HasAnnotation("Relational:JsonPropertyName", "Period");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("Recorder")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Recorder_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ВидЦены_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Номенклатура_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Упаковка_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("Цена")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("InformationRegister_ЦеныНоменклатуры_RecordType", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.InformationRegister.InformationRegisterЦеныНоменклатурыЗакупочныеSliceLast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<DateTime>("Period")
                        .HasColumnType("datetime2");

                    b.Property<string>("Номенклатура_Key")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("Цена")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("InformationRegister_ЦеныНоменклатуры_Закупочные_SliceLast", (string)null);
                });

            modelBuilder.Entity("WH.Domain.Models.Catalog.CatalogПартнерыВидыДеятельности", b =>
                {
                    b.HasOne("WH.Domain.Models.Catalog.CatalogПартнеры", null)
                        .WithMany("Доброга_ВидыДеятельности")
                        .HasForeignKey("Ref_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WH.Domain.Models.Document.DocumentЗаказКлиентаТовары", b =>
                {
                    b.HasOne("WH.Domain.Models.Document.DocumentЗаказКлиента", null)
                        .WithMany("Товары")
                        .HasForeignKey("Ref_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WH.Domain.Models.Document.DocumentОтчетОРозничныхПродажахТовары", b =>
                {
                    b.HasOne("WH.Domain.Models.Document.DocumentОтчетОРозничныхПродажах", null)
                        .WithMany("Товары")
                        .HasForeignKey("Ref_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WH.Domain.Models.Document.DocumentРеализацияТоваровУслугТовары", b =>
                {
                    b.HasOne("WH.Domain.Models.Document.DocumentРеализацияТоваровУслуг", null)
                        .WithMany("Товары")
                        .HasForeignKey("Ref_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WH.Domain.Models.Catalog.CatalogПартнеры", b =>
                {
                    b.Navigation("Доброга_ВидыДеятельности");
                });

            modelBuilder.Entity("WH.Domain.Models.Document.DocumentЗаказКлиента", b =>
                {
                    b.Navigation("Товары");
                });

            modelBuilder.Entity("WH.Domain.Models.Document.DocumentОтчетОРозничныхПродажах", b =>
                {
                    b.Navigation("Товары");
                });

            modelBuilder.Entity("WH.Domain.Models.Document.DocumentРеализацияТоваровУслуг", b =>
                {
                    b.Navigation("Товары");
                });
#pragma warning restore 612, 618
        }
    }
}
